x-uffizzi:
  ingress:
    service: aiomusic
    port: 8080
services:
  aiomusic:
    image: aiomusic:latest
    build: .
    environment:
      TG_BOT_TOKEN: ""
      APP_ID: ""
      API_HASH: ""
      AUTH_CHAT: ""
      ADMINS: ""
      IS_BOT_PUBLIC: ""
      BOT_USERNAME: ""
      DATABASE_URL: ""
      MENTION_USERS: ""
      ANIT_SPAM_MODE: ""
      TIDAL_EMAIL: ""
      TIDAL_PASSWORD: ""
      QOBUZ_EMAIL: ""
      QOBUZ_PASSWORD: ""
    deploy:
      resources:
        limits:
          memory: 4000M
